trigger: 
- master

pool:
  vmImage: ubuntu-latest

#variables:
#  imageName: 'pipelines-ns-docker'


steps:

    
- task: Docker@2
  displayName: "Docker Login to docker_registry"
  inputs:
    containerRegistry: 'docker_registry'
    command: 'login'


- task: Docker@2
  displayName: "Docker Build"
  inputs:
    containerRegistry: 'docker_registry'
    repository: 'organizationname/reponamefrontend'
    command: 'build'
    Dockerfile: 'docker/Dockerfile'
    buildContext: '.'


- task: Docker@2
  displayName: "Docker Push"
  inputs:
    containerRegistry: 'docker_registry'
    repository: 'organizationname/reponamefrontend'
    command: 'push'



- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'ACR01'
    repository: '$(imageRepo)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
          $(tag)



########################
## K8s config
########################


- task: Bash@3
  displayName: "Set tag version in K8S configuration"
  inputs:
    targetType: 'inline'
    script: 'sed -i "s/\:latest/\:$(Build.BuildId)/g; s/\:fixed-latest/\:latest/g" $(System.DefaultWorkingDirectory)/k8s/dev-deployment.yaml'
    

- task: Bash@3
  displayName: "Set tag version in K8S configuration"
  inputs:
    targetType: 'inline'
    script: 'sed -i "s/\:latest/\:$(Build.BuildId)/g; s/\:fixed-latest/\:latest/g" $(System.DefaultWorkingDirectory)/k8s/test-deployment.yaml'



- task: Bash@3
  displayName: "Set tag version in K8S configuration"
  inputs:
    targetType: 'inline'
    script: 'sed -i "s/\:latest/\:$(Build.BuildId)/g; s/\:fixed-latest/\:latest/g" $(System.DefaultWorkingDirectory)/k8s/prod-deployment.yaml'


########################
## 
########################


- task: CopyFiles@2
  displayName: "Copy Kubernetes Manifest"
  inputs:
    sourceFolder: $(System.DefaultWorkingDirectory)/k8s/
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifact'
    publishLocation: 'Container'


########################
## K8s Manifest
########################

- task: KubernetesManifest@0
  displayName: "k8s manifest"
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'clusterdev-sc'
    namespace: 'default'
    manifests: 'k8s/dev-deployment.yaml'


- task: KubernetesManifest@0
  displayName: "k8s manifest"
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'clustertest-sc'
    namespace: 'default'
    manifests: 'k8s/test-deployment.yaml'
    
- task: KubernetesManifest@0
  displayName: "k8s manifest"
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'clusterprod-sc'
    namespace: 'default'
    manifests: 'k8s/prod-deployment.yaml'
