trigger:
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: ubuntu-latest




steps:

- task: Docker@2
  displayName: "Login to ACR"
  inputs:
    containerRegistry: 'ACR01'
    command: 'login'

- task: DownloadPipelineArtifact@2
  displayName: Download Pipeline artifacts
  inputs:
  buildType: 'current'
  artifactName: 'manifests-docker'
  itemPattern: |
            Dockerfile
  targetPath: '$(Pipeline.Workspace)/manifests-docker'


- task: Docker@2
  displayName: "Docker Build"
  inputs:
    containerRegistry: 'ACR01'
    repository: 'organizationname/reponamefrontend'
    command: 'build'
    Dockerfile: './Dockerfile'
    buildContext: '.'


- task: Docker@2
  displayName: "Docker Push"
  inputs:
    containerRegistry: 'ACR01'
    repository: 'organizationname/reponame'
    command: 'push'



- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'ACR01'
    repository: 'app'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      1.0.$(Build.BuildId)
      latest



########################
## K8s config
########################


- task: Bash@3
  displayName: "Set tag version in K8S configuration"
  inputs:
    targetType: 'inline'
    script: 'sed -i "s/\:latest/\:$(Build.BuildId)/g; s/\:fixed-latest/\:latest/g" $(System.DefaultWorkingDirectory)/k8s/dev-deployment.yaml'
    

- task: Bash@3
  displayName: "Set tag version in K8S configuration"
  inputs:
    targetType: 'inline'
    script: 'sed -i "s/\:latest/\:$(Build.BuildId)/g; s/\:fixed-latest/\:latest/g" $(System.DefaultWorkingDirectory)/k8s/test-deployment.yaml'



- task: Bash@3
  displayName: "Set tag version in K8S configuration"
  inputs:
    targetType: 'inline'
    script: 'sed -i "s/\:latest/\:$(Build.BuildId)/g; s/\:fixed-latest/\:latest/g" $(System.DefaultWorkingDirectory)/k8s/prod-deployment.yaml'


########################
## Publish manifest as Artifact
########################

#- task: DownloadPipelineArtifact@2
#  inputs:
#    buildType: 'current'
#    artifactName: 'manifests'
#    targetPath: '$(Pipeline.Workspace)/manifests'


- task: CopyFiles@2
  displayName: "Copy Kubernetes Manifest"
  inputs:
    sourceFolder: $(System.DefaultWorkingDirectory)/k8s/
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifact'
    publishLocation: 'Container'


########################
## K8s Manifest
########################

- task: KubernetesManifest@0
  displayName: "k8s manifest"
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'clusterdev-sc'
    namespace: 'default'
    manifests: 'k8s/dev-deployment.yaml'


- task: KubernetesManifest@0
  displayName: "k8s manifest"
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'clustertest-sc'
    namespace: 'default'
    manifests: 'k8s/test-deployment.yaml'
    
- task: KubernetesManifest@0
  displayName: "k8s manifest"
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'clusterprod-sc'
    namespace: 'default'
    manifests: 'k8s/prod-deployment.yaml'
