---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration 
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  
- name: copy the sample page
  template: src=index.html dest=/usr/share/nginx/html/index.html

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: start service
  service: name=nginx state=started enabled=yes
