apiVersion : apps/v1
kind: Deployment
metadata:
  name: sampleapp 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp 
    spec:
      containers:
        - name: sampleapp 
          image: ACR01.azurecr.io/sampleapp
          imagePullPolicy: Always
          ports:
          - containerPort: 80 
      imagePullSecrets:
      - name: dockerpullsecret
---

apiVersion: v1
kind: Service
metadata:
    name: app-service
    labels:
      app: app-service
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
    selector:
        app: app
