apiVersion : apps/v1
kind: Deployment
metadata:
  name: prod-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app 
    spec:
      containers:
        - name: prod-app-image
          image: ACR01.azurecr.io/sampleapp
          imagePullPolicy: Always
          ports:
          - containerPort: 80 
      imagePullSecrets:
      - name: dockerpullsecret
---

apiVersion: v1
kind: Service
metadata:
    name: test-service
    labels:
      app: test-service
spec:
#    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
    selector:
        app: prod-app 
