trigger: 
- master


resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'XXXXXXXX-XXXXXX-XXXXXXXX-XXXXX-XXXXX'
  imageRepository: 'web'
  containerRegistry: 'lab.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'


pool:
  vmImage: ubuntu-latest
  
  
stages:
- stage: Build
  displayName: Build & Push image
  jobs:
  - job: Build
    displayName: Build-job1
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Push to registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceCnnection)
        tags:
  
