trigger: 
- master

pool:
  vmImage: ubuntu-latest
  
- task: Docker@2
  displayName: "Docker Login to Paterva's Docker registry"
  inputs:
    containerRegistry: 'Paterva_docker_registry'
    command: 'login'
    
- task: Docker@2
  displayName: "Docker Build"
  inputs:
    containerRegistry: 'docker_registry'
    repository: 'organizationname/reponame'
    command: 'build'
    Dockerfile: 'docker/Dockerfile'
    buildContext: '.'
    
- task: Docker@2
  displayName: "Docker Push"
  inputs:
    containerRegistry: 'docker_registry'
    repository: 'organizationname/reponamefrontend'
    command: 'push'

- task: Bash@3
  displayName: "Set tag version in K8S configuration"
  inputs:
    targetType: 'inline'
    script: 'sed -i "s/\:latest/\:$(Build.BuildId)/g; s/\:fixed-latest/\:latest/g" $(System.DefaultWorkingDirectory)/k8s.yaml'
