trigger: 
- none
resources:
- repo: self
pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: build
    displayName: build-job1
    steps:
    - task: Docker@2
      displayName: "Docker Build"
      inputs:
        containerregistrytype: 'Azure Container Registry'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'


- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push-job2
    steps:
    - task: Docker@2
      displayName: "Docker Push"
      inputs:
        containerregistrytype: 'Azure Container Registry'
        command: 'push'


- stage: Compose
  displayName: Compose
  jobs:
  - job: Compose
    displayName: Compose-job2
    steps:
    - task: DockerCompose@0
      displayName: Build images
      inputs:
        containerregistrytype: 'Azure Container Registry'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up --build'


- stage: Deploy_to_dev_environment 
  displayName: 'Deploy to Dev'
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs: 
                azureSubscription: 'XXXXXXXXXXXXXXXXXXX'
                appName: 'app1'
                appType: webAppLinux
                package: '$(Pipeline.Workspace)/**/*.zip'
