# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acceleration-calc
  labels:
    app: acceleration-calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acceleration-calc
  template:
    metadata:
      labels:
        app: acceleration-calc
    spec:
      containers:
        - name: acceleration-calc
          image: <DOCKER_IMAGE>
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          command: ["yarn", "start"]

---

# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: acceleration-calc
  labels:
    app: acceleration-calc
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: acceleration-calc

