apiVersion: v1
kind: Service
metadata:
  name: acceleration-calc-service
spec:
  type: NodePort
  selector:
    app: acceleration-calc
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
