--
- name: Install node and npm
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
          
- name: Check Node version
  command: node -v
  ignore_errors: true

- name: Check NPM version
  command: npm -v
  ignore_errors: true
