trigger:
- main

resources:
- repo: self


variables:
  imageRepo: app
  tag: '$(Build.BuildId)'
  kubernetesServiceConnection: clusterdev
  kubernetesServiceConnection: clustertest
  kubernetesServiceConnection: clusterprod



stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'ACR01'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'
